### ISSUE TITLE
Colors?

### ISSUE THREAD

**Issue by Waterspark63** [MrHuds0n/dotfiles#1]
Any chance we can get the color palette used for the hacknet theme? I'm trying to get it setup on my machine, but I'm not really sure where the colors are defined/if they are custom set values. If you don't have the colors anymore, no worries. Thank you.

**Comment by zanlib0** [comment]
@Waterspark63 sorry, I didn't see the notification for a while - the colours were generated using [pywal](https://github.com/dylanaraps/pywal) and pretty sure that I loaded them with .Xresources but it's been a long time and I don't remember
